<?php
/**
* @file myApp.module
*
* Implements an AngularJS-driven block.
*/

/**
* Implements hook_block_info().
*/
function myApp_block_info() {
  $blocks['weather'] = array(
    'info' => t('Weather'),
    );
  return $blocks;
}

/**
* Implements hook_block_view().
*/
function myApp_block_view($delta = '') {
  $block = array();

  switch($delta){
    case 'weather':
      $path = drupal_get_path('module', 'myApp');
      $block['subject'] = t('Weather status.');
      $block['content'] = array(
        '#theme' => 'weather_status',
        '#attached' => array(
          'js' => array(
            '//cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.10/angular.js',
            $path . '/myApp.js',
            ),
          ),
        );
      break;
  }
  return $block;
}

/**
* Implements hook_theme().
*/
function myApp_theme() {
  return array(
    'weather_status' => array(
      'template' => 'weather-status',
      'variables' => array(),
      ),
    );
}
